# Generated by Django 4.2.5 on 2023-11-12 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baju', models.CharField(max_length=100)),
                ('kaos', models.CharField(max_length=100)),
                ('kemeja', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='aplikasi_utama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toko', models.CharField(max_length=100)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikasi_utama.kategori')),
            ],
        ),
    ]
